CREATE TABLE users (id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1),
                     name VARCHAR(255) NOT NULL,
                     passwd VARCHAR(255) NOT NULL,
                     PRIMARY KEY (id));